const chatbotResponses: string[] = [
    "Alright, let me think on that for a moment. Hang tight!",
    "Give me just a sec, I'm pulling up something for you now.",
    "One moment—I'm putting my brain to work on this!",
    "Let me check on that for you real quick. Won't be long!",
    "Good question! Let me work on that—should have something shortly.",
    "Hold tight, I'm working on getting you a great answer.",
    "Let me process that real quick, give me just a second.",
    "I hear you! Let me see what I can come up with.",
    "Just a sec, I'm piecing something together for you.",
    "Hang on a moment, I'm gathering the best info for you!",
    "Great question! Let me put some thought into that.",
    "Give me a moment, I'm pulling some data together.",
    "Let me crunch some numbers and get back to you real quick!",
    "Hmm, let me think… I'll have an answer for you soon!",
    "Processing that now—just a few seconds!",
    "Let me dive into that, I'll have something for you shortly!",
    "Alright, let me run some calculations—give me a sec!",
    "One sec, I'm on it!",
    "Let me check my sources and get back to you in a moment.",
    "Good one! Let me work through that real quick.",
    "Just a moment, I'm figuring that out for you!",
    "Stay with me, I'm pulling up some details!",
    "One second, just making sure I get this right for you.",
    "Let me think through this—shouldn't take too long!",
    "I'm working on that now! Sit tight for a few seconds.",
    "Let me dig into that for you—won't be long!",
    "I’m on it! Just need a moment to put it together.",
    "Good question! Let me make sure I get the best answer for you.",
    "One sec, just checking a few things for you!",
    "Alright, let me double-check something—give me a sec.",
    "Hold on, just pulling up the right info for you!",
    "I got you! Just need a little time to work this out.",
    "Hmm, interesting. Give me a moment to process it!",
    "Just a few seconds and I'll have something for you.",
    "I'm cooking up an answer—hang tight for a sec!",
    "One moment! I’ll have something for you soon.",
    "Let me make sure I have the best answer—just a moment!",
    "Hang tight, I’m verifying something real quick.",
    "Let me gather my thoughts for a second!",
    "I’m thinking on that—give me just a little time!",
    "Good one! Let me get my thoughts in order real quick.",
    "I’m running some quick checks—be right with you!",
    "That’s an interesting one! Let me take a second to think.",
    "Let me gather the best info for you—just a sec!",
    "Give me a sec, making sure I get this right!",
    "Processing your request—won't take long!",
    "One moment, pulling up the best response for you!",
    "Let me put my thinking cap on—give me a second!",
    "Hold up, I need a moment to piece this together!",
    "I’m putting the pieces together—hang tight for a sec!",
    "One sec, I want to make sure I give you the best response.",
    "I need just a moment to work this out—hold on!",
    "On it! Just need a moment to process that.",
    "Give me a little time to pull together the best answer!",
    "That’s a good one! Let me put some thought into it.",
    "I’m working on a solid answer for you—hang tight!",
    "Let me piece this together—just a moment!",
    "Give me a few seconds, I’ll be right back with you.",
    "Let me gather my best response—won’t take long!",
    "I need a sec to make sure I get this right!",
    "On it! Let me take a moment to work this through.",
    "That’s a great question! Give me a sec to process it.",
    "Hang tight! I’m working on something for you.",
    "One moment, I’m making sure I get the details right.",
    "I’ll have an answer for you soon—just a moment!",
    "Checking a few things—stay with me for a sec!",
    "I’m running a few calculations—hang tight!",
    "Give me just a bit, I want to get this right for you.",
    "One moment, I’m getting this figured out for you.",
    "Let me put some thought into this—won’t take long!",
    "I’m processing that now—give me a second!",
    "I’ll be right back with an answer—one moment!",
    "Working through that now—just a little patience!",
    "I got this! Just need a little time to get it right.",
    "Let me analyze that—just a short wait!",
    "Processing now! I’ll have something soon.",
    "Give me a moment, I’m putting the pieces together.",
    "I’m almost there—just a few more seconds!",
    "One sec, I need a bit of time to think on that.",
    "Let me double-check a few things—won’t take long!",
    "Hang on, I’m making sure I get this right!",
    "Great question! Let me work through that quickly.",
    "I’ll have something for you in just a moment!",
    "Stay with me—I’m putting something together now!",
    "I’m checking a few things—just a short wait!",
    "Give me a second to organize my response!",
    "Let me do some quick thinking—won’t be long!",
    "I hear you! Let me put my thoughts together for a sec.",
    "Just a sec—I want to make sure this is solid!",
    "I’m diving into that now—shouldn’t be long!",
    "One sec, I’m getting things sorted for you.",
    "Let me sift through the info—be right with you!",
    "Give me a sec, I want to be thorough with this one!",
    "I’ll be back with an answer shortly—one moment!",
    "That’s a tricky one! Let me think through it.",
    "I need a few moments to check something!",
    "Just a moment, I’m ensuring accuracy for you!",
  ];
  
  export default chatbotResponses;
  